-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 14:52:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema makeitreal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema makeitreal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `makeitreal` DEFAULT CHARACTER SET utf8mb3 ;
USE `makeitreal` ;

-- -----------------------------------------------------
-- Table `makeitreal`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeitreal`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `makeitreal`.`emprendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeitreal`.`emprendedor` (
  `idEmprendedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `imagenPerfil` BLOB NOT NULL,
  PRIMARY KEY (`idEmprendedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `makeitreal`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeitreal`.`proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaCreación` DATE NOT NULL,
  `objetivo` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `masInformacion` VARCHAR(45) NOT NULL,
  `metaFinanciamiento` FLOAT NOT NULL,
  `cantidadRecaudada` FLOAT NOT NULL,
  `id_Categoria` INT NOT NULL,
  `id_Emprendedor` INT NOT NULL,
  PRIMARY KEY (`idProyecto`),
  INDEX `idCategoria_idx` (`id_Categoria` ASC) VISIBLE,
  INDEX `idEmprendedor_idx` (`id_Emprendedor` ASC) VISIBLE,
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`id_Categoria`)
    REFERENCES `makeitreal`.`categoria` (`idCategoria`),
  CONSTRAINT `idEmprendedor`
    FOREIGN KEY (`id_Emprendedor`)
    REFERENCES `makeitreal`.`emprendedor` (`idEmprendedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `makeitreal`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeitreal`.`comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(80) NOT NULL,
  `fecha` DATE NOT NULL,
  `calificacion` INT NOT NULL,
  `id_Proyecto` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `idProyecto_idx` (`id_Proyecto` ASC) VISIBLE,
  CONSTRAINT `idProyectoF`
    FOREIGN KEY (`id_Proyecto`)
    REFERENCES `makeitreal`.`proyecto` (`idProyecto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `makeitreal`.`imagenproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeitreal`.`imagenproyecto` (
  `idimagenProyecto` INT NOT NULL AUTO_INCREMENT,
  `imagen` BLOB NOT NULL,
  `idProyecto` INT NOT NULL,
  PRIMARY KEY (`idimagenProyecto`),
  INDEX `idProyecto_idx` (`idProyecto` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `makeitreal`.`proyecto` (`idProyecto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `makeitreal`.`patrocinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeitreal`.`patrocinador` (
  `idPatrocinador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `imagenPerfil` BLOB NOT NULL,
  `proyectosPatrocinador` INT NOT NULL,
  `montoTotalPatrocinado` FLOAT NOT NULL,
  `experienciaProyectos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPatrocinador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `makeitreal`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeitreal`.`pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `monto` FLOAT NOT NULL,
  `fecha` DATE NOT NULL,
  `método` VARCHAR(45) NOT NULL,
  `concepto` VARCHAR(45) NOT NULL,
  `id_Patrocinador` INT NOT NULL,
  `id_Proyecto` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `idPatrocinador_idx` (`id_Patrocinador` ASC) VISIBLE,
  INDEX `idProyecto_idx` (`id_Proyecto` ASC) VISIBLE,
  CONSTRAINT `idPatrocinador`
    FOREIGN KEY (`id_Patrocinador`)
    REFERENCES `makeitreal`.`patrocinador` (`idPatrocinador`),
  CONSTRAINT `idProyecto`
    FOREIGN KEY (`id_Proyecto`)
    REFERENCES `makeitreal`.`proyecto` (`idProyecto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
